using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Chemistry;
using Content.Shared.Chemistry.Reagent;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Linq;
using Content.Shared.Chemistry.Components;
using Content.Shared.Chemistry.EntitySystems;
using Content.Shared.FixedPoint;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client.Chemistry.UI
{
    /// <summary>
    /// Client-side UI used to control a <see cref="SolutionContainerMixerComponent"/>
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class CentrifugeWindow : FancyWindow
    {
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
        public event Action<BaseButton.ButtonEventArgs, CentrifugeWindow.ReagentButton>? OnReagentButtonPressed;

        /// <summary>
        /// Create and initialize the chem master UI client-side. Creates the basic layout,
        /// actual data isn't filled in until the server sends data about the chem master.
        /// </summary>
        public CentrifugeWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
        }

        /// <summary>
        /// Update the UI state when new state data is received from the server.
        /// </summary>
        /// <param name="state">State data sent by the server.</param>
        public void UpdateState(BoundUserInterfaceState state)
        {
            var castState = (CentrifugeBoundUserInterfaceState) state;
            UpdatePanelInfo(castState);

            ToggleBusyDisableOverlayPanel(castState.IsBusy);
            InputEjectButton.Disabled = castState.InputContainerInfo is null;
        }

        /// <summary>
        /// Update the container, buffer, and packaging panels.
        /// </summary>
        /// <param name="state">State data for the dispenser.</param>
        private void UpdatePanelInfo(CentrifugeBoundUserInterfaceState state)
        {
            BuildContainerUI(InputContainerInfo, state.InputContainerInfo);

            BufferInfo.Children.Clear();

            if (!state.BufferReagents.Any())
            {
                BufferInfo.Children.Add(new Label { Text = Loc.GetString("chem-master-window-buffer-empty-text") });

                return;
            }

            var bufferHBox = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal
            };
            BufferInfo.AddChild(bufferHBox);

            var bufferLabel = new Label { Text = $"{Loc.GetString("chem-master-window-buffer-label")} " };
            bufferHBox.AddChild(bufferLabel);
            var bufferVol = new Label
            {
                Text = $"{state.BufferCurrentVolume}u",
                StyleClasses = {StyleNano.StyleClassLabelSecondaryColor}
            };
            bufferHBox.AddChild(bufferVol);

            foreach (var (reagent, quantity) in state.BufferReagents)
            {
                // Try to get the prototype for the given reagent. This gives us its name.
                _prototypeManager.TryIndex(reagent.Prototype, out ReagentPrototype? proto);
                var name = proto?.LocalizedName ?? Loc.GetString("chem-master-window-unknown-reagent-text");

                if (proto != null)
                {
                    BufferInfo.Children.Add(new BoxContainer
                    {
                        Orientation = LayoutOrientation.Horizontal,
                        Children =
                        {
                            new Label {Text = $"{name}: "},
                            new Label
                            {
                                Text = $"{quantity}u",
                                StyleClasses = {StyleNano.StyleClassLabelSecondaryColor}
                            },

                            // Padding
                            new Control {HorizontalExpand = true},

                            MakeReagentButton(
                                Loc.GetString("solution-container-mixer-window-dump-button"),
                                reagent,
                                false,
                                StyleBase.ButtonOpenLeft
                            ),
                            MakeReagentButton(
                                Loc.GetString("solution-container-mixer-window-all-amount-button"),
                                reagent,
                                true,
                                StyleBase.ButtonOpenLeft
                            ),
                        }
                    });
                }
            }
        }

        private ReagentButton MakeReagentButton(string text, ReagentId id, bool isTransfer, string styleClass)
        {
            var button = new ReagentButton(text, id, isTransfer, styleClass);
            button.OnPressed +=
                args => OnReagentButtonPressed?.Invoke(args, button);
            return button;
        }

        private void BuildContainerUI(Control control, ContainerInfo? info)
        {
            control.Children.Clear();

            if (info is null)
            {
                control.Children.Add(new Label
                {
                    Text = Loc.GetString("chem-master-window-no-container-loaded-text")
                });
            }
            else
            {
                // Name of the container and its fill status (Ex: 44/100u)
                control.Children.Add(new BoxContainer
                {
                    Orientation = LayoutOrientation.Horizontal,
                    Children =
                    {
                        new Label {Text = $"{info.DisplayName}: "},
                        new Label
                        {
                            Text = $"{info.CurrentVolume}/{info.MaxVolume}",
                            StyleClasses = {StyleNano.StyleClassLabelSecondaryColor}
                        }
                    }
                });

                IEnumerable<(string Name, ReagentId Id, FixedPoint2 Quantity)> contents;

                if (info.Entities != null)
                {
                    contents = info.Entities.Select(x => (x.Id, default(ReagentId), x.Quantity));
                }
                else if (info.Reagents != null)
                {
                    contents = info.Reagents.Select(x =>
                    {
                        _prototypeManager.TryIndex(x.Reagent.Prototype, out ReagentPrototype? proto);
                        var name = proto?.LocalizedName
                                   ?? Loc.GetString("chem-master-window-unknown-reagent-text");

                        return (name, Id: x.Reagent, x.Quantity);
                    })
                        .OrderBy(r => r.Item1);
                }
                else
                {
                    return;
                }


                foreach (var (name, id, quantity) in contents)
                {
                    var inner = new BoxContainer
                    {
                        Orientation = LayoutOrientation.Horizontal,
                        Children =
                        {
                            new Label { Text = $"{name}: " },
                            new Label
                            {
                                Text = $"{quantity}u",
                                StyleClasses = { StyleNano.StyleClassLabelSecondaryColor },
                            }
                        }
                    };

                    control.Children.Add(inner);
                }

            }
        }

        public void ToggleBusyDisableOverlayPanel(bool shouldDisable)
        {
            DisableCookingPanelOverlay.Visible = shouldDisable;
        }

        public sealed class ReagentButton : Button
        {
            public bool IsTransfer { get; set; }
            public ReagentId Id { get; set; }
            public ReagentButton(string text, ReagentId id, bool isTransfer, string styleClass)
            {
                AddStyleClass(styleClass);
                Text = text;
                Id = id;
                IsTransfer = isTransfer;
            }
        }
    }

}
